# Site settings
title: Austin Meyer, PhD, MS
email: austin.g.meyer_at_gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Visiting Scholar<br>
  Center for Comp. Biology and Bioinformatics<br>
  The University of Texas at Austin<br>
  2500 Speedway, A4800<br>
  Room: MBB 3.232
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.meyerlab.org" # the base hostname & protocol for your site
twitter_username: austingmeyer
github_username:  ausmeyer

# Build settings
markdown: kramdown

